trigger:
- development

pool:
  vmImage: ubuntu-latest

variables:
  -group: 'bookings-common'

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: CopyFiles@2
            displayName: 'Copy bicep files'
            inputs:
              SourceFolder: 'Bicep'
              Contents: '*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish bicep files'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
              
  - stage: DEV
    variables:
      -group: 'bookings-dev'
    jobs:
      - job: Deploy
        steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download bicep files'
            inputs:
              buildType: current
              downloadType: single
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: AzureCLI@2
            displayName: 'Az cli deployment'
            inputs:
              azureSubscription: 'Azure service connection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: | 
                az deployment sub create \
                  --location $(location) \
                  --subscription $(subscriptionId) \ 
                  --template-file main.bicep \
                  --parameters \
                    dbAdminPassword=$(dbAdminPassword) \
                    sendGridApiKey=$(sendGridApiKey) \
                    appSecret=$(appSecret)
              workingDirectory: '$(System.ArtifactsDirectory)'
