name: $(BuildDefinitionName)

trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    jobs:
      - job: Build
        steps:
          - task: CopyFiles@2
            displayName: 'Copy bicep files'
            inputs:
              SourceFolder: 'Bicep'
              Contents: '*'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          
          - task: PublishBuildArtifacts@1
            displayName: 'Publish bicep files'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
              
  - stage: DEV
    variables:
      - group: bookings-dev
      - group: bookings-common
    jobs:
      - job: Deploy
        steps:         
          - task: DownloadBuildArtifacts@1
            displayName: 'Download bicep files'
            inputs:
              buildType: current
              downloadType: single
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - script: ls $(System.ArtifactsDirectory)/drop